In [6]:
my_list = [1, "Hello", 3.4, [1,2,3]]
print(my_list[3][2])

3


In [7]:
my_list = ['p','r','o','g','r','a','m','i','z']
# elements 3rd to 5th
print(my_list[2:5])

# elements beginning to 4th
print(my_list[:-5])

# elements 6th to end
print(my_list[5:])

# elements beginning to end
print(my_list[:])

['o', 'g', 'r']
['p', 'r', 'o', 'g']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [25]:
odd = [1, 9]
odd.insert(1,3)

# Output: [1, 3, 9] 
#print(odd)

odd[2:2] = [5, 7]

# Output: [1, 3, 5, 7, 9]
print(odd)

[1, 3, 5, 7, 9]


In [26]:
my_list = ['p','r','o','b','l','e','m']
my_list.remove('p')

# Output: ['r', 'o', 'b', 'l', 'e', 'm']
print(my_list)

# Output: 'o'
print(my_list.pop(1))

# Output: ['r', 'b', 'l', 'e', 'm']
print(my_list)

# Output: 'm'
print(my_list.pop())

# Output: ['r', 'b', 'l', 'e']
print(my_list)

my_list.clear()

# Output: []
print(my_list)

['r', 'o', 'b', 'l', 'e', 'm']
o
['r', 'b', 'l', 'e', 'm']
m
['r', 'b', 'l', 'e']
[]


In [29]:
import array as arr
a = arr.array('d', [1.1, 3.5, 4.5])
print(a)

array('d', [1.1, 3.5, 4.5])


In [31]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[ 1.1  2.   3. ]
 [ 3.   4.   5. ]]
[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]


In [36]:
import numpy as np

zeors_array = np.zeros( (2, 3) )
print(zeors_array)

ones_array = np.ones( (1, 5), dtype=np.int32 )
print(ones_array)

ones_array = np.ones( (2, 5, 4), dtype=np.int32 )
print(ones_array)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 1 1 1 1]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [37]:
import numpy as np

A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

''' 
Output:
A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
'''

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


' \nOutput:\nA = [0 1 2 3]\nB = [[ 0  1  2  3  4  5]\n [ 6  7  8  9 10 11]]\n'